/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Mr4yuf8Kqf8
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { ChatList } from "./chat-list";

export function ChatInterface({ children }: { children: React.ReactNode }) {
  return (
    <div className="grid grid-cols-[1fr_4fr] h-screen w-full">
      <div className="bg-gray-100 dark:bg-gray-900 border-r border-gray-200 dark:border-gray-800 overflow-auto">
        <div className="p-4 space-y-4">
          <ChatList />
        </div>
      </div>
      <div>{children}</div>
    </div>
  );
}
